### ISSUE TITLE
Add option for common anode/cathode

### ISSUE THREAD

**Issue by asergunov** [asergunov/7segment_gpio#8]
Add option for common anode/cathode so user will not need to invert pins one by one

**Comment by I-hate-2FA** [comment]
https://gitlab.com/ailife8881/7segment-gpio

**Comment by asergunov** [comment]
Awesome! You can open PR to contribute to this repo.

**Comment by I-hate-2FA** [comment]
i cant upload code on github, because account might get locked, my other account @AILIFE4798 is locked for login now, because it force you to enable 2fa, so this account will stay for comment only, you can just copy the code from gitlab and upload it here, then i can delete the repo on gitlab

**Comment by asergunov** [comment]
I see. Give me second. I’ll pull your branch.

BTW I think you can use gitlab in your tests if you like.

Ср, 3 июля 2024 г. в 15:56, AILIFE ***@***.***>:

**Comment by I-hate-2FA** [comment]
yes i have used
```yaml
external_components:
  - source:
      type: git
      url: https://gitlab.com/ailife8881/7segment-gpio
      ref: main
    refresh: 0s  
```
